apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /nginx(/|$)(.*)
          backend:
            serviceName: nginx-service
            servicePort: 5679
